<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 3px solid #7c3aed;
            padding-bottom: 20px;
        }

        .header h1 {
            color: #7c3aed;
            font-size: 24px;
            margin: 0 0 5px 0;
            font-weight: bold;
        }

        .header h2 {
            color: #666;
            font-size: 14px;
            margin: 0;
            font-weight: normal;
        }

        .meta-info {
            display: flex;
            justify-content: space-between;
            margin-bottom: 25px;
            font-size: 11px;
            color: #666;
        }

        .filters {
            background: #f8fafc;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 25px;
            border-left: 4px solid #7c3aed;
        }

        .filters h3 {
            margin: 0 0 10px 0;
            color: #7c3aed;
            font-size: 14px;
        }

        .stats-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 15px;
            margin-bottom: 30px;
        }

        .stat-card {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
        }

        .stat-card.pending { background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); }
        .stat-card.approved { background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); }
        .stat-card.completed { background: linear-gradient(135deg, #43e97b 0%, #38f9d7 100%); }
        .stat-card.rejected { background: linear-gradient(135deg, #fa709a 0%, #fee140 100%); }

        .stat-number {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 5px;
        }

        .stat-label {
            font-size: 11px;
            opacity: 0.9;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            font-size: 10px;
        }

        th {
            background: #7c3aed;
            color: white;
            padding: 8px 6px;
            text-align: left;
            font-weight: bold;
            border: 1px solid #6d28d9;
        }

        td {
            padding: 6px;
            border: 1px solid #e5e7eb;
            vertical-align: top;
        }

        tr:nth-child(even) {
            background: #f9fafb;
        }

        tr:hover {
            background: #f3f4f6;
        }

        .status-badge {
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 9px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .status-pending { background: #fef3c7; color: #92400e; }
        .status-approved { background: #d1fae5; color: #065f46; }
        .status-completed { background: #dbeafe; color: #1e40af; }
        .status-rejected { background: #fee2e2; color: #991b1b; }
        .status-awaiting { background: #e0e7ff; color: #3730a3; }

        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #9ca3af;
            border-top: 1px solid #e5e7eb;
            padding-top: 15px;
        }

        .page-break {
            page-break-before: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <h2>{{ $subtitle }}</h2>
    </div>

    <div class="meta-info">
        <div>
            <strong>Generated By:</strong> {{ $generatedBy }}<br>
            <strong>Export Date:</strong> {{ $exportDate->format('d M Y H:i:s') }}
        </div>
        <div>
            <strong>Total Records:</strong> {{ $requests->count() }}<br>
            <strong>Report Type:</strong> Summary Overview
        </div>
    </div>

    @if($filters['status'] || $filters['search'])
        <div class="filters">
            <h3>Applied Filters</h3>
            @if($filters['status'])
                <strong>Status:</strong> {{ ucwords(str_replace('_', ' ', $filters['status'])) }}<br>
            @endif
            @if($filters['search'])
                <strong>Search:</strong> "{{ $filters['search'] }}"<br>
            @endif
            <strong>Applied At:</strong> {{ $filters['applied_at']->format('d M Y H:i:s') }}
        </div>
    @endif

    <div class="stats-grid">
        <div class="stat-card">
            <div class="stat-number">{{ $stats['total_requests'] }}</div>
            <div class="stat-label">Total Requests</div>
        </div>
        <div class="stat-card pending">
            <div class="stat-number">{{ $stats['pending_requests'] }}</div>
            <div class="stat-label">Pending Review</div>
        </div>
        <div class="stat-card approved">
            <div class="stat-number">{{ $stats['approved_requests'] }}</div>
            <div class="stat-label">Approved</div>
        </div>
        <div class="stat-card completed">
            <div class="stat-number">{{ $stats['completed_requests'] }}</div>
            <div class="stat-label">Completed</div>
        </div>
    </div>

    <div class="stats-grid">
        <div class="stat-card rejected">
            <div class="stat-number">{{ $stats['rejected_requests'] }}</div>
            <div class="stat-label">Rejected</div>
        </div>
        <div class="stat-card pending">
            <div class="stat-number">{{ $stats['talent_awaiting_admin'] }}</div>
            <div class="stat-label">Talent Awaiting Admin</div>
        </div>
        <div class="stat-card approved">
            <div class="stat-number">{{ $stats['admin_awaiting_talent'] }}</div>
            <div class="stat-label">Admin Awaiting Talent</div>
        </div>
        <div class="stat-card completed">
            <div class="stat-number">{{ $stats['both_accepted'] }}</div>
            <div class="stat-label">Both Parties Accepted</div>
        </div>
    </div>

    <h3 style="color: #7c3aed; margin-bottom: 15px; font-size: 16px;">Talent Requests Overview</h3>

    <table>
        <thead>
            <tr>
                <th style="width: 6%;">ID</th>
                <th style="width: 20%;">Recruiter</th>
                <th style="width: 20%;">Talent</th>
                <th style="width: 15%;">Status</th>
                <th style="width: 12%;">Project End</th>
                <th style="width: 12%;">Created</th>
                <th style="width: 15%;">Last Updated</th>
            </tr>
        </thead>
        <tbody>
            @foreach($requests as $request)
                <tr>
                    <td>#{{ $request->id }}</td>
                    <td>
                        @if($request->recruiter && $request->recruiter->user)
                            <strong>{{ $request->recruiter->user->name }}</strong><br>
                            <small>{{ $request->recruiter->company_name ?: 'N/A' }}</small>
                        @else
                            <em>Unknown Recruiter</em>
                        @endif
                    </td>
                    <td>
                        @if($request->talent && $request->talent->user)
                            <strong>{{ $request->talent->user->name }}</strong><br>
                            <small>{{ $request->talent->user->email }}</small>
                        @else
                            <em>Unknown Talent</em>
                        @endif
                    </td>
                    <td>
                        @php
                            $statusClass = 'status-pending';
                            $displayStatus = $request->getUnifiedDisplayStatus();

                            if (str_contains(strtolower($displayStatus), 'approved') || str_contains(strtolower($displayStatus), 'setuju')) {
                                $statusClass = 'status-approved';
                            } elseif (str_contains(strtolower($displayStatus), 'completed') || str_contains(strtolower($displayStatus), 'selesai')) {
                                $statusClass = 'status-completed';
                            } elseif (str_contains(strtolower($displayStatus), 'rejected') || str_contains(strtolower($displayStatus), 'tolak')) {
                                $statusClass = 'status-rejected';
                            } elseif (str_contains(strtolower($displayStatus), 'waiting') || str_contains(strtolower($displayStatus), 'menunggu')) {
                                $statusClass = 'status-awaiting';
                            }
                        @endphp
                        <span class="status-badge {{ $statusClass }}">
                            {{ $displayStatus }}
                        </span>
                    </td>
                    <td>
                        @php
                            $endDate = null;
                            $endSource = '';

                            if ($request->project && $request->project->expected_end_date) {
                                $endDate = $request->project->expected_end_date;
                                $endSource = 'Project';
                            } elseif ($request->project_end_date) {
                                $endDate = $request->project_end_date;
                                $endSource = 'Request';
                            }
                        @endphp

                        @if($endDate)
                            <strong>{{ $endDate->format('d M Y') }}</strong><br>
                            <small>({{ $endSource }})</small>
                        @else
                            <em>Not specified</em>
                        @endif
                    </td>
                    <td>
                        <strong>{{ $request->created_at->format('d M Y') }}</strong><br>
                        <small>{{ $request->created_at->format('H:i') }}</small>
                    </td>
                    <td>
                        <strong>{{ $request->updated_at->format('d M Y') }}</strong><br>
                        <small>{{ $request->updated_at->format('H:i') }}</small>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    @if($requests->isEmpty())
        <div style="text-align: center; padding: 40px; color: #9ca3af;">
            <h3>No Requests Found</h3>
            <p>No talent requests match the current filter criteria.</p>
        </div>
    @endif

    <div class="footer">
        <p>This report was generated automatically by the Talent Admin System on {{ $exportDate->format('F j, Y \a\t g:i A') }}</p>
        <p>© {{ date('Y') }} WebPelatihan - Talent Management System</p>
    </div>
</body>
</html>
