<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            font-size: 11px;
            line-height: 1.3;
            color: #333;
            margin: 0;
            padding: 15px;
        }

        .header {
            text-align: center;
            margin-bottom: 25px;
            border-bottom: 3px solid #7c3aed;
            padding-bottom: 15px;
        }

        .header h1 {
            color: #7c3aed;
            font-size: 22px;
            margin: 0 0 5px 0;
            font-weight: bold;
        }

        .header h2 {
            color: #666;
            font-size: 13px;
            margin: 0;
            font-weight: normal;
        }

        .meta-info {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
            font-size: 10px;
            color: #666;
        }

        .filters {
            background: #f8fafc;
            padding: 12px;
            border-radius: 6px;
            margin-bottom: 20px;
            border-left: 4px solid #7c3aed;
        }

        .filters h3 {
            margin: 0 0 8px 0;
            color: #7c3aed;
            font-size: 13px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
            font-size: 9px;
        }

        th {
            background: #7c3aed;
            color: white;
            padding: 6px 4px;
            text-align: left;
            font-weight: bold;
            border: 1px solid #6d28d9;
            font-size: 8px;
        }

        td {
            padding: 5px 4px;
            border: 1px solid #e5e7eb;
            vertical-align: top;
        }

        tr:nth-child(even) {
            background: #f9fafb;
        }

        .status-badge {
            padding: 2px 4px;
            border-radius: 3px;
            font-size: 7px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .status-pending { background: #fef3c7; color: #92400e; }
        .status-approved { background: #d1fae5; color: #065f46; }
        .status-completed { background: #dbeafe; color: #1e40af; }
        .status-rejected { background: #fee2e2; color: #991b1b; }
        .status-awaiting { background: #e0e7ff; color: #3730a3; }

        .metrics-box {
            background: #f0f9ff;
            border: 1px solid #0ea5e9;
            padding: 4px;
            border-radius: 3px;
            font-size: 8px;
        }

        .redflag-indicator {
            background: #fef2f2;
            color: #dc2626;
            padding: 1px 3px;
            border-radius: 2px;
            font-size: 7px;
            font-weight: bold;
        }

        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 9px;
            color: #9ca3af;
            border-top: 1px solid #e5e7eb;
            padding-top: 10px;
        }

        .page-break {
            page-break-before: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <h2>{{ $subtitle }}</h2>
    </div>

    <div class="meta-info">
        <div>
            <strong>Generated By:</strong> {{ $generatedBy }}<br>
            <strong>Export Date:</strong> {{ $exportDate->format('d M Y H:i:s') }}
        </div>
        <div>
            <strong>Total Records:</strong> {{ $total_count }}<br>
            <strong>Report Type:</strong> Detailed Analysis
        </div>
    </div>

    @if($filters['status'] || $filters['search'])
        <div class="filters">
            <h3>Applied Filters</h3>
            @if($filters['status'])
                <strong>Status:</strong> {{ ucwords(str_replace('_', ' ', $filters['status'])) }}<br>
            @endif
            @if($filters['search'])
                <strong>Search:</strong> "{{ $filters['search'] }}"<br>
            @endif
            <strong>Applied At:</strong> {{ $filters['applied_at']->format('d M Y H:i:s') }}
        </div>
    @endif

    <h3 style="color: #7c3aed; margin-bottom: 12px; font-size: 14px;">Detailed Talent Requests Analysis</h3>

    <table>
        <thead>
            <tr>
                <th style="width: 4%;">ID</th>
                <th style="width: 15%;">Recruiter Info</th>
                <th style="width: 15%;">Talent Info</th>
                <th style="width: 10%;">Status</th>
                <th style="width: 12%;">Project Details</th>
                <th style="width: 10%;">Timeline</th>
                <th style="width: 8%;">Projects</th>
                <th style="width: 8%;">Red Flags</th>
                <th style="width: 18%;">Performance Metrics</th>
            </tr>
        </thead>
        <tbody>
            @foreach($requests as $request)
                <tr>
                    <td>#{{ $request['id'] }}</td>
                    <td>
                        <strong>{{ $request['recruiter_name'] }}</strong><br>
                        <small>{{ $request['recruiter_company'] }}</small>
                    </td>
                    <td>
                        <strong>{{ $request['talent_name'] }}</strong><br>
                        <small>{{ $request['talent_email'] }}</small>
                    </td>
                    <td>
                        @php
                            $statusClass = 'status-pending';
                            $displayStatus = $request['status'];

                            if (str_contains(strtolower($displayStatus), 'approved') || str_contains(strtolower($displayStatus), 'setuju')) {
                                $statusClass = 'status-approved';
                            } elseif (str_contains(strtolower($displayStatus), 'completed') || str_contains(strtolower($displayStatus), 'selesai')) {
                                $statusClass = 'status-completed';
                            } elseif (str_contains(strtolower($displayStatus), 'rejected') || str_contains(strtolower($displayStatus), 'tolak')) {
                                $statusClass = 'status-rejected';
                            } elseif (str_contains(strtolower($displayStatus), 'waiting') || str_contains(strtolower($displayStatus), 'menunggu')) {
                                $statusClass = 'status-awaiting';
                            }
                        @endphp
                        <span class="status-badge {{ $statusClass }}">
                            {{ $displayStatus }}
                        </span><br>
                        <small style="font-size: 7px;">
                            T: {{ $request['talent_accepted'] ? 'Yes' : 'No' }} |
                            A: {{ $request['admin_accepted'] ? 'Yes' : 'No' }}
                        </small>
                    </td>
                    <td>
                        <strong>{{ $request['project_title'] }}</strong><br>
                        <small>End: {{ $request['project_end_date'] }}</small>
                    </td>
                    <td>
                        <small>Created: {{ $request['created_at'] }}</small><br>
                        <small>Updated: {{ $request['updated_at'] }}</small>
                        @if($request['workflow_completed_at'])
                            <br><small>Completed: {{ $request['workflow_completed_at'] }}</small>
                        @endif
                    </td>
                    <td style="text-align: center;">
                        <strong>{{ $request['talent_project_count'] }}</strong><br>
                        <small>Projects</small>
                    </td>
                    <td style="text-align: center;">
                        @if($request['talent_redflag_count'] > 0)
                            <span class="redflag-indicator">{{ $request['talent_redflag_count'] }} Flags</span>
                        @else
                            <small>None</small>
                        @endif
                    </td>
                    <td>
                        @if($request['talent_metrics'])
                            <div class="metrics-box">
                                <strong>Performance:</strong><br>
                                <small>                                    Velocity: {{ round(floatval($request['talent_metrics']['learning_velocity'] ?? 0)) }}%<br>
                                    Consistency: {{ round(floatval($request['talent_metrics']['consistency'] ?? 0)) }}%<br>
                                    Adaptability: {{ round(floatval($request['talent_metrics']['adaptability'] ?? 0)) }}%
                                </small>
                            </div>
                        @else
                            <small>No metrics available</small>
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    @if(empty($requests) || count($requests) === 0)
        <div style="text-align: center; padding: 30px; color: #9ca3af;">
            <h3>No Requests Found</h3>
            <p>No talent requests match the current filter criteria.</p>
        </div>
    @endif

    <div class="page-break"></div>

    <!-- Summary Analysis Section -->
    <h3 style="color: #7c3aed; margin-bottom: 15px; font-size: 16px;">Analysis Summary</h3>

    @php
        $totalRequests = count($requests);
        $avgProjectCount = $totalRequests > 0 ? round(collect($requests)->avg('talent_project_count'), 1) : 0;
        $totalRedflags = collect($requests)->sum('talent_redflag_count');
        $redflagRate = $totalRequests > 0 ? round(($totalRedflags / $totalRequests) * 100, 1) : 0;

        $statusDistribution = collect($requests)->groupBy('status_raw')->map(function($group) {
            return $group->count();
        });

        $avgMetrics = [
            'velocity' => 0,
            'consistency' => 0,
            'adaptability' => 0
        ];
          $metricsCount = 0;
        foreach ($requests as $request) {
            if (isset($request['talent_metrics']) && $request['talent_metrics'] && is_array($request['talent_metrics'])) {
                $avgMetrics['velocity'] += floatval($request['talent_metrics']['learning_velocity'] ?? 0);
                $avgMetrics['consistency'] += floatval($request['talent_metrics']['consistency'] ?? 0);
                $avgMetrics['adaptability'] += floatval($request['talent_metrics']['adaptability'] ?? 0);
                $metricsCount++;
            }
        }

        if ($metricsCount > 0) {
            $avgMetrics['velocity'] = round($avgMetrics['velocity'] / $metricsCount, 1);
            $avgMetrics['consistency'] = round($avgMetrics['consistency'] / $metricsCount, 1);
            $avgMetrics['adaptability'] = round($avgMetrics['adaptability'] / $metricsCount, 1);
        }
    @endphp

    <table style="margin-top: 15px;">
        <thead>
            <tr>
                <th colspan="2" style="text-align: center; background: #4f46e5;">Key Performance Indicators</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="width: 50%; font-weight: bold;">Total Requests Analyzed</td>
                <td style="width: 50%; text-align: center;">{{ $totalRequests }}</td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Average Projects per Talent</td>
                <td style="text-align: center;">{{ $avgProjectCount }}</td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Total Red Flags</td>
                <td style="text-align: center;">{{ $totalRedflags }}</td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Red Flag Rate</td>
                <td style="text-align: center;">{{ $redflagRate }}%</td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Average Learning Velocity</td>
                <td style="text-align: center;">{{ $avgMetrics['velocity'] }}%</td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Average Consistency</td>
                <td style="text-align: center;">{{ $avgMetrics['consistency'] }}%</td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Average Adaptability</td>
                <td style="text-align: center;">{{ $avgMetrics['adaptability'] }}%</td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        <p>This detailed report was generated automatically by the Talent Admin System on {{ $exportDate->format('F j, Y \a\t g:i A') }}</p>
        <p>© {{ date('Y') }} WebPelatihan - Talent Management System</p>
    </div>
</body>
</html>
